In [1]:
import os
os.listdir()

['.ipynb_checkpoints', 'ANN.ipynb', 'Churn_Modelling.csv']

In [2]:
#DATA PREPROCESSING
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,Imputer,StandardScaler
from sklearn.metrics import confusion_matrix

In [3]:
#converting categorical data to dummy variable
dataset=pd.read_csv('Churn_Modelling.csv')
y=dataset.iloc[:,-1]
dataset=dataset.drop(columns=['RowNumber','CustomerId','Surname','Exited'])
text=[]
numeric=[]

string=dataset.select_dtypes(include='object').columns

for i in string:
    x=dataset[i].nunique()
    if x<5 and x>0:
        dataset=pd.get_dummies(dataset,columns=[i])
dataset

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0
5,645,44,8,113755.78,2,1,0,149756.71,0,0,1,0,1
6,822,50,7,0.00,2,1,1,10062.80,1,0,0,0,1
7,376,29,4,115046.74,4,1,0,119346.88,0,1,0,1,0
8,501,44,4,142051.07,2,0,1,74940.50,1,0,0,0,1
9,684,27,2,134603.88,1,1,1,71725.73,1,0,0,0,1
10,528,31,6,102016.72,2,0,0,80181.12,1,0,0,0,1
11,497,24,3,0.00,2,1,0,76390.01,0,0,1,0,1
12,476,34,10,0.00,2,1,0,26260.98,1,0,0,1,0
13,549,25,5,0.00,2,0,0,190857.79,1,0,0,1,0
14,635,35,7,0.00,2,1,1,65951.65,0,0,1,1,0
15,616,45,3,143129.41,2,0,1,64327.26,0,1,0,0,1
16,653,58,1,132602.88,1,1,0,5097.67,0,1,0,0,1
17,549,24,9,0.00,2,1,1,14406.41,0,0,1,1,0
18,587,45,6,0.00,1,0,0,158684.81,0,0,1,0,1
19,726,24,6,0.00,2,1,1,54724.03,1,0,0,1,0
20,732,41,8,0.00,2,1,1,170886.17,1,0,0,0,1
21,636,32,8,0.00,2,1,0,138555.46,0,0,1,1,0
22,510,38,4,0.00,1,1,0,118913.53,0,0,1,1,0
23,669,46,3,0.00,2,0,1,8487.75,1,0,0,0,1
24,846,38,5,0.00,1,1,1,187616.16,1,0,0,1,0
25,577,25,3,0.00,2,0,1,124508.29,1,0,0,0,1
26,756,36,2,136815.64,1,1,1,170041.95,0,1,0,0,1
27,571,44,9,0.00,2,0,0,38433.35,1,0,0,0,1
28,574,43,3,141349.43,1,1,1,100187.43,0,1,0,1,0
29,411,29,0,59697.17,2,1,1,53483.21,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,518,42,7,151027.05,2,1,0,119377.36,1,0,0,0,1
9971,833,34,3,144751.81,1,0,0,166472.81,1,0,0,1,0
9972,758,26,4,155739.76,1,1,0,171552.02,1,0,0,0,1
9973,611,27,7,0.00,2,1,1,157474.10,1,0,0,0,1
9974,583,33,7,122531.86,1,1,0,13549.24,1,0,0,0,1
9975,610,50,1,113957.01,2,1,0,196526.55,0,1,0,0,1
9976,637,33,7,103377.81,1,1,0,84419.78,1,0,0,1,0
9977,683,32,9,0.00,2,1,1,24991.92,1,0,0,1,0
9978,774,40,9,93017.47,2,1,0,191608.97,1,0,0,0,1
9979,677,58,1,90022.85,1,0,1,2988.28,1,0,0,1,0
9980,741,35,6,74371.49,1,0,0,99595.67,0,0,1,0,1
9981,498,42,3,152039.70,1,1,1,53445.17,0,1,0,0,1
9982,655,46,7,137145.12,1,1,0,115146.40,0,1,0,1,0
9983,613,40,4,0.00,1,0,0,151325.24,1,0,0,0,1
9984,602,35,7,90602.42,2,1,1,51695.41,0,1,0,0,1
9985,659,36,6,123841.49,2,1,0,96833.00,1,0,0,0,1
9986,673,47,1,183579.54,2,0,1,34047.54,0,1,0,0,1
9987,606,30,8,180307.73,2,1,1,1914.41,0,0,1,0,1
9988,775,30,4,0.00,2,1,0,49337.84,1,0,0,0,1
9989,841,28,4,0.00,2,1,1,179436.60,0,0,1,0,1
9990,714,33,3,35016.60,1,1,0,53667.08,0,1,0,0,1
9991,597,53,4,88381.21,1,1,0,69384.71,1,0,0,1,0
9992,726,36,2,0.00,1,1,0,195192.40,0,0,1,0,1
9993,644,28,7,155060.41,1,1,0,29179.52,1,0,0,0,1
9994,800,29,2,0.00,2,0,0,167773.55,1,0,0,1,0
9995,771,39,5,0.00,2,1,0,96270.64,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,0,1,0

In [4]:
X=dataset.values
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [5]:


#encoding categorical data
#labelencoder_X_1=LabelEncoder()
#abelencoder_X_2=LabelEncoder()
#X[:,2]=labelencoder_X_1.fit_transform(X[:, 2])
#onehotencoder=OneHotEncoder(categorical_features=(1))
#X=onehotencoder.fit_transform(X).toarray()


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=0)
X_train
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [6]:
#importing the libraries
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\Users\sachin\Anaconda3\envs\tf\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [7]:
#Initialising ANN
classifier = Sequential()

In [8]:
#Adding input layer units tell how many nodes you have to take
#input_dim=no. of independent variables
classifier.add(Dense(units=6,activation='relu',kernel_initializer='uniform',input_dim=13))

In [9]:
#Adding hidden layer
classifier.add(Dense(units=6,activation='relu',kernel_initializer='uniform'))

In [10]:
#as it is output layer so units=1 as we have 1 dependent variable
classifier.add(Dense(units=1,activation='sigmoid'))

In [11]:
#compiling ANN
#optimizer is the algorithm you want to use to make the ANN more powerful 
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:From C:\Users\sachin\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\ops\nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [12]:
#Fitting the ANN to training set
#batch_size is the no. of observation after which you want to change the weight
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

C:\Users\sachin\Anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until

Epoch 1/100
7500/7500 [==============================] - 2s 266us/step - loss: 0.4811 - accuracy: 0.7955
Epoch 2/100
7500/7500 [==============================] - 1s 101us/step - loss: 0.4312 - accuracy: 0.7963
Epoch 3/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4248 - accuracy: 0.7968
Epoch 4/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4203 - accuracy: 0.8176
Epoch 5/100
7500/7500 [==============================] - 1s 127us/step - loss: 0.4174 - accuracy: 0.8243
Epoch 6/100
7500/7500 [==============================] - 1s 124us/step - loss: 0.4153 - accuracy: 0.8295
Epoch 7/100
7500/7500 [==============================] - 1s 115us/step - loss: 0.4135 - accuracy: 0.8299
Epoch 8/100
7500/7500 [==============================] - 1s 97us/step - loss: 0.4119 - accuracy: 0.8327
Epoch 9/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4111 - accuracy: 0.8336
Epoch 10/100
7500/7500 [==============================] - 1s 95us/step - loss: 0.4101 - accuracy: 0.8331
Epoch 11/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4089 - accuracy: 0.8329
Epoch 12/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4083 - accuracy: 0.8341
Epoch 13/100
7500/7500 [==============================] - 1s 93us/step - loss: 0.4077 - accuracy: 0.8340
Epoch 14/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4077 - accuracy: 0.8328
Epoch 15/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.4071 - accuracy: 0.8341
Epoch 16/100
7500/7500 [==============================] - 1s 95us/step - loss: 0.4068 - accuracy: 0.8353
Epoch 17/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4065 - accuracy: 0.8339
Epoch 18/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4053 - accuracy: 0.8347
Epoch 19/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4056 - accuracy: 0.8345
Epoch 20/100
7500/7500 [==============================] - 1s 101us/step - loss: 0.4055 - accuracy: 0.8332
Epoch 21/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.4048 - accuracy: 0.8356
Epoch 22/100
7500/7500 [==============================] - 1s 118us/step - loss: 0.4049 - accuracy: 0.8345
Epoch 23/100
7500/7500 [==============================] - 1s 111us/step - loss: 0.4046 - accuracy: 0.8348
Epoch 24/100
7500/7500 [==============================] - 1s 97us/step - loss: 0.4044 - accuracy: 0.8344
Epoch 25/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4043 - accuracy: 0.8343
Epoch 26/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4038 - accuracy: 0.8339
Epoch 27/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4039 - accuracy: 0.8349
Epoch 28/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4036 - accuracy: 0.8351
Epoch 29/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4036 - accuracy: 0.8340
Epoch 30/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4035 - accuracy: 0.8348
Epoch 31/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4036 - accuracy: 0.8336
Epoch 32/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4033 - accuracy: 0.8348
Epoch 33/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4034 - accuracy: 0.8343
Epoch 34/100
7500/7500 [==============================] - 1s 105us/step - loss: 0.4027 - accuracy: 0.8333
Epoch 35/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.4031 - accuracy: 0.8349
Epoch 36/100
7500/7500 [==============================] - 1s 129us/step - loss: 0.4029 - accuracy: 0.8337
Epoch 37/100
7500/7500 [==============================] - 1s 94us/step - loss: 0.4029 - accuracy: 0.8332
Epoch 38/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4029 - accuracy: 0.8339
Epoch 39/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4025 - accuracy: 0.8340
Epoch 40/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4028 - accuracy: 0.8345
Epoch 41/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4024 - accuracy: 0.8332
Epoch 42/100
7500/7500 [==============================] - 1s 102us/step - loss: 0.4026 - accuracy: 0.8327
Epoch 43/100
7500/7500 [==============================] - 1s 102us/step - loss: 0.4028 - accuracy: 0.8319
Epoch 44/100
7500/7500 [==============================] - 1s 117us/step - loss: 0.4029 - accuracy: 0.8340
Epoch 45/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4027 - accuracy: 0.8340
Epoch 46/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4023 - accuracy: 0.8341
Epoch 47/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4028 - accuracy: 0.8329
Epoch 48/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4016 - accuracy: 0.8327
Epoch 49/100
7500/7500 [==============================] - 1s 101us/step - loss: 0.4025 - accuracy: 0.8339
Epoch 50/100
7500/7500 [==============================] - 1s 102us/step - loss: 0.4022 - accuracy: 0.8344
Epoch 51/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.4024 - accuracy: 0.8333
Epoch 52/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4019 - accuracy: 0.8351
Epoch 53/100
7500/7500 [==============================] - 1s 107us/step - loss: 0.4024 - accuracy: 0.8336
Epoch 54/100
7500/7500 [==============================] - 1s 107us/step - loss: 0.4020 - accuracy: 0.8341
Epoch 55/100
7500/7500 [==============================] - 1s 109us/step - loss: 0.4020 - accuracy: 0.8337
Epoch 56/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4018 - accuracy: 0.8331
Epoch 57/100
7500/7500 [==============================] - 1s 108us/step - loss: 0.4023 - accuracy: 0.8333
Epoch 58/100
7500/7500 [==============================] - 1s 94us/step - loss: 0.4019 - accuracy: 0.8323
Epoch 59/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4021 - accuracy: 0.8344
Epoch 60/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4024 - accuracy: 0.8328
Epoch 61/100
7500/7500 [==============================] - 1s 102us/step - loss: 0.4022 - accuracy: 0.8339
Epoch 62/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4021 - accuracy: 0.8324
Epoch 63/100
7500/7500 [==============================] - 1s 107us/step - loss: 0.4021 - accuracy: 0.8344
Epoch 64/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4021 - accuracy: 0.8332
Epoch 65/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4015 - accuracy: 0.8332
Epoch 66/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.4024 - accuracy: 0.8327
Epoch 67/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.4017 - accuracy: 0.8349
Epoch 68/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4012 - accuracy: 0.8352
Epoch 69/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4019 - accuracy: 0.8341
Epoch 70/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.4015 - accuracy: 0.8360
Epoch 71/100
7500/7500 [==============================] - 1s 107us/step - loss: 0.4018 - accuracy: 0.8343
Epoch 72/100
7500/7500 [==============================] - 1s 105us/step - loss: 0.4016 - accuracy: 0.8341
Epoch 73/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4012 - accuracy: 0.8341
Epoch 74/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4021 - accuracy: 0.8333
Epoch 75/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4014 - accuracy: 0.8331
Epoch 76/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4019 - accuracy: 0.8340
Epoch 77/100
7500/7500 [==============================] - 1s 109us/step - loss: 0.4012 - accuracy: 0.8339
Epoch 78/100

7500/7500 [==============================] - 1s 110us/step - loss: 0.4017 - accuracy: 0.8336
Epoch 79/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4015 - accuracy: 0.8352
Epoch 80/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.4014 - accuracy: 0.8351
Epoch 81/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.4011 - accuracy: 0.8324
Epoch 82/100
7500/7500 [==============================] - 1s 105us/step - loss: 0.4017 - accuracy: 0.8359
Epoch 83/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4018 - accuracy: 0.8329
Epoch 84/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4017 - accuracy: 0.8356
Epoch 85/100
7500/7500 [==============================] - 1s 108us/step - loss: 0.4008 - accuracy: 0.8337
Epoch 86/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4016 - accuracy: 0.8343
Epoch 87/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4009 - accuracy: 0.8336
Epoch 88/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4010 - accuracy: 0.8347
Epoch 89/100
7500/7500 [==============================] - 1s 94us/step - loss: 0.4010 - accuracy: 0.8335
Epoch 90/100
7500/7500 [==============================] - 1s 94us/step - loss: 0.4014 - accuracy: 0.8355
Epoch 91/100
7500/7500 [==============================] - 1s 96us/step - loss: 0.4014 - accuracy: 0.8335
Epoch 92/100
7500/7500 [==============================] - 1s 98us/step - loss: 0.4016 - accuracy: 0.8331
Epoch 93/100
7500/7500 [==============================] - 1s 97us/step - loss: 0.4010 - accuracy: 0.8339
Epoch 94/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4014 - accuracy: 0.8333
Epoch 95/100
7500/7500 [==============================] - 1s 101us/step - loss: 0.4009 - accuracy: 0.8340
Epoch 96/100
7500/7500 [==============================] - 1s 97us/step - loss: 0.4010 - accuracy: 0.8359
Epoch 97/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.4006 - accuracy: 0.8340
Epoch 98/100
7500/7500 [==============================] - 1s 101us/step - loss: 0.4014 - accuracy: 0.8333
Epoch 99/100
7500/7500 [==============================] - 1s 99us/step - loss: 0.4013 - accuracy: 0.8347
Epoch 100/100
7500/7500 [==============================] - 1s 100us/step - loss: 0.4007 - accuracy: 0.8343

In [13]:
y_pred=classifier.predict(X_test)

In [14]:
ypred=pd.DataFrame(y_pred)
ypred

             0
0     0.201344
1     0.371256
2     0.216590
3     0.072877
4     0.180632
5     0.854737
6     0.100774
7     0.090654
8     0.213433
9     0.855987
10    0.068062
11    0.193174
12    0.250178
13    0.157583
14    0.487285
15    0.362704
16    0.363534
17    0.146366
18    0.119180
19    0.250207
20    0.470598
21    0.047059
22    0.182479
23    0.157866
24    0.040813
25    0.209350
26    0.116305
27    0.181001
28    0.082310
29    0.486826
...        ...
2470  0.738068
2471  0.407165
2472  0.734594
2473  0.361764
2474  0.134592
2475  0.025523
2476  0.132055
2477  0.373619
2478  0.221482
2479  0.061381
2480  0.049671
2481  0.117390
2482  0.223140
2483  0.859243
2484  0.107207
2485  0.187144
2486  0.137142
2487  0.103784
2488  0.351366
2489  0.037177
2490  0.694084
2491  0.149147
2492  0.206786
2493  0.062602
2494  0.174947
2495  0.328406
2496  0.613462
2497  0.293185
2498  0.267076
2499  0.067749

[2500 rows x 1 columns]

In [15]:
y_pred=(y_pred>0.5)

In [16]:
cm=confusion_matrix(y_test,y_pred)

In [17]:
cm

array([[1928,   63],
       [ 323,  186]], dtype=int64)

In [18]:
acc=(1939+174)/2500

In [19]:
acc

0.8452